init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap
#  - cmd: R -q -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
#  - cmd: R -q -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
#  - cmd: R -q -e "if (!requireNamespace('curl', quietly = TRUE)) install.packages('curl')"
#  - cmd: R -q -e "remotes::install_github('ropenscilabs/tic')"
#  - cmd: R -q -e "tic::prepare_all_stages()"
#  - cmd: R -q -e "tic::before_install()"


build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_r Rcpp

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits


version: 1.0.{build}-{branch}

branches:
  only:
    - master
    - release
    - dev

skip_tags: true

max_jobs: 1
#platform: x64
#image: Visual Studio 2017

#environment:
#  global:
#    USE_RTOOLS: true
#    R_ARCH: x64
#    WARNINGS_ARE_ERRORS: true

cache:
  - C:\RLibrary\

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
  
  - provider: Slack
    incoming_webhook:
      secure: B6xB+HL9BbAzIABcCOxdDHCBL1q3bSx5LGXnD+lprcLQOQQsqVU3g94BgP+otpnt+40N8UoAx8o0/eaDA4A3SXCMgLG/jVIlS0mtWxmM8Po=
