language: r
sudo: false
dist: trusty

branches:
  only:
  - master
  - release
  
os:
  - linux
  - osx

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
    
notifications:
  slack:
    secure: TU9iwragCwu6tO02ja3zDRxcuftj340NdvWH8GplhWCMeowJ2/k8qTufFNB47PRK3qSUqOqDQqR16KE1u/JNTBQHsAhKM9lpLQ6NWI1PKx0QjKQqYN+8tqEHJaw7/xaOmgoqP7AojdTUiyIYipw9OFkyrLbMgGUYg16D2H7dvQ9MmzRJf3nDyzpdgUuZEnDi5PQR1VoJhHogKbFKFqR79u94HmkQ2S+LIFvYsb48K0bWsMIMhFgDIutjhlG4rLMdzzzDTFr8dx++u9B8FnIWSRop9XiY8dp1Cyz0Ru1KCqQ0skLPL9wlx9HcI3ptCwHm1VSEmB8cSTL9GHPronTP8ZgyWKJZ2glmToWWycN5gEgWqpI8nBnKithCKolzfN4vaH4Dh9qIOuAK7rUQZl50vyU7/kimqDq4zPXLhkdJXr+bIR0yBu3TfzIJrnNPv1tor8tlcf1o2Oc6ppVqCyDsk3XK4l6EuGk5BoJXJ2u9Kci7/Kvzi8Fre8DgRHG+qjJmdOPqv6dzeUMDNFJ9bBc/lXUe8PNyF8eH9M77AeZdgzzZ7LYGBUi8kbQ4KZa5wPvaxs/giURDioua6Vq8sfy0g4CVAtbN7NkHAez5QLordtHavZrnIV/Sq13vy/nJxXxMMogVEgITCpVUHVyGTNyd0MNUlrLXAJkFIRJ4eE+FY04=
    on_success: always
    on_failure: always
    on_pull_requests: false
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
  email: false
