language: r
sudo: false
dist: trusty

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
