language: r
sudo: false
dist: trusty

branches:
  only:
  - master
  - release
  
os:
  - linux
  - osx

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
    
notifications:
  slack:
    rooms:
      - secure: "V4OQsUKWonFPMHtbNbKwCRPHBgWx4Na0IrtI6ZKXxWlOR0+nO9IdKZOkjSBUQWdZhvu02qhRqOsrTYiM/4ZYzUoobr42arC0wDt9Wxd6HTyrkQZ8WWivKSIXMnPhd8cpweFpEpcOQZYqwnd9oBzB3TkToSt6mNYbhmnhXEMOnuAx/2vBiaXEbXIdIIKO8Um1DWBLIbdnpC2BpAq1frLj+xLPaNthLniCPchNTgcP/hKYr3ndA/IHXwTwoeTxk3IR2c4+OUYWV3p6DFYoM9wuJhsEPuGXAilqwVj74BAouSLgmiTFmXKBHhTDEEmrmphnre7eLO68nMuBQHrs/l8vE2B3amVcTicZu9cMJqkq2nJc0McvWjHrrPV5mK5uNgpQfbcMfQrMB+uxsATN5uBjF2IpwFOXKVf1OTAbWtf4bd77QYMFmnlUP5uphy7FS+6KtMXmJ+aX2H7/i5AvyGUMgAovBPUgo6p2mr09BOuWbUreJIaq2yjaqCpEWGdBtcofjGvPVdZlY0tFzg38IReKBqmmD/S4dP4Nk4tUaAm5r82vTXFcQr/J8y0mFPO+xIypJ1IpFHmFSltH3dIVKtW1poXe2GXZv8NOUho+l63wsi/y//NiKAQlBaNxDn2j691Bt73c+o9rm36FPaFHe7ypdiK7/e+bvoWAIzoGbfYTouc="
    on_success: always
    on_failure: always
    on_pull_requests: false
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
  email: false
