language: r
sudo: false
dist: trusty

branches:
  only:
  - master
  - release
  
os:
  - linux
  - osx

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
    
notifications:
  slack:
    rooms:
      - secure: "ZL+j/Q3zXCYWtIMpU4BLvjxaptEbEvL5TEkrCARerBjZhReyZN8MqqN4Ok3MO9kfGShMqez7shEDoDwFiiTjySQtUpoOZYqAovzkBhMY441Cd/2TG80p+c/UvQqrenHJ6nW2FEkxrvixhq9yQpyAIrLMKg0/Xg+glfhkZnIL5cRQaTc3rCJGftwmTmGCD0tV9FBfYzd0QUC/BJaDmrX6zZ/uO/C/zcpAT33ioV1s69yd6KLJB4jX7n1DbG8KVEHJFys+cMkUYBhg0XLPmRN+uCt7S5BQlFGEzJvxCZBOQdnqrpEHADG92fGlCQavGPVjTBB3Hk1mhlZPEruXhOHhsphUlkJBXuoN4zkb3+Vmc5/GDDt5CxrC+scwWU8R2IpiTfWpyyjAthabfDm/G0Wfsgz3lluGAAHFbqjOre2+4jslNGZdy4WJJintxRGKMGFRpNXTHYkzCTyfJHxoePDpQQFDDkYpEh9WsAcgOdFBFTCx/lD74VL3uDohRpTyVUMc+CJDo7awcVtwf3FlxH7vexbxvoBNfDKPBtlBxM8i2beehKPBsdZm4TsUrIYjxQCbS2fqvlVoEWtvBZM3FShf5ODhATildNqIir6LXFfFMtHVPcKbPnGsN5TXKTQrvjYBLRM0wMxE3ej3XW5js+eqjZlfutOVylP6dTZKaSubFeU="
    on_success: always
    on_failure: always
    on_pull_requests: false
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
  email: false
