language: r
sudo: false
dist: trusty

# whitelist
branches:
  only:
    - master
    - release
    - dev

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
    
notifications:
  slack:
    on_success: change
    on_failure: always
  email:
    on_success: change
    on_failure: change
    on_failure: change
