language: r
sudo: false
dist: trusty

branches:
  only:
  - master
  - release
  
#os:
#  - linux
#  - osx

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
    
notifications:
  slack:
    - distr6:IcBmMQxhN01OILBOggRT4Tge
#    rooms:
#      - secure: "mfDcEz63wIRx/7+P1AdHiIv/NJqThbkIOgKx1M7TRmToLeXe9cd2aO3kdAE7STO3tL5sRZKvlAYxH17DsPC8KIAKMrAiWJUAMnZ6GZGw0AoGVUhDsom+DroUl4gTUYxqUT1ErjMJI8QQ9441JTdcny828pCwG8LEhh2c+8UZM42uJpurRJqx+dkMAKRCDeo3RGVu3FUxARypFvtAK7gA9YTMWuhamwXwXiNhY7TQv6E5zwU/HdHnkmAz4TsphZQ+ad49/7DHmdzG+OV8DG+/7J5LKf4AdeLfsmCOsYF2Qp9lyCbjG/z3jMfzf9cgpX8ysOW7zOOFYLBX+4Dfw6F0Xi1W2o60OrUo+gJimbsW/l9RXJ9ub/0/OAasCEsXWdRGO0T4B/do6Id1XmFB0e/uKX1UJG+oAzhjjHDKvUhtUj8iq4IOI5zoIZVN6mWCwU/4gUVGh03I5+GFFJbcIzCsqpE3V3znh15iKv+gcEEaLDOBZ0XhitPpZDHUz650OMyKUoFcTaBY11O0+nvVsgSerbEccyU286DiwA20x/3txgC6f63JCmR+bA6+y0Q1WepwjbCXLAPBOrykrmI23vqMiClM55twKyl+BFVeKwW7F9/W8O+ItOi+CCbcs4WScas6+rIUr8TKYG8znKgCNn0Bir+kiMrKhRVyROqivIEJLbc="
    on_success: always
    on_failure: always
    on_pull_requests: false
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
  email: false
